### ISSUE TITLE
Build is failing with latest release of ja-yaml-4.0.0

### ISSUE THREAD

**Issue by sailu-naredla** [Tomtomgo/constangular-brunch#5]
[exec] 02 Feb 03:28:00 - [31merror[0m: Compiling of 'app/config/api.yaml' failed. Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default. ; Compiling of 'app/config/env.yaml' failed. Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.

Can you please address this issue and fix accordingly. big Thanks

**Comment by Nickesh** [comment]
Same here. The latest version breaks my projects. An update would be appreciated.

**Comment by sailu-naredla** [comment]
Nikesh - I have done the workaround  by enforcing previous version using  npm install constangular-brunch js-yaml@3.13.1

**Comment by sailu-naredla** [comment]
> Same here. The latest version breaks my projects. An update would be appreciated.

Nikesh - I have done with workaround by enforcing previous version using npm install constangular-brunch js-yaml@3.13.1

also inlude the below entries in package.json file. 
  "scripts": {
    "preinstall": "npx npm-force-resolutions"
  },

"resolutions": {
    "js-yaml": "3.13.1"
  },

**Comment by Nickesh** [comment]
@sailu-naredla, first thanks for a super quick answer!

Unfortunately the solution didn't work in my case :(

`npm install` still stubbornly downloads version 4 of `js-yaml` as `constangular-brunch` dependency. Of course I wipe out the whole `node_modules` directory and etc.

It seems so simple to fix in the library and just issue a new version.

**Comment by Tomtomgo** [comment]
Hi all, I am not actively maintaining this project. If you would like to submit a fix, I'm happy to merge it though.

**Comment by Nickesh** [comment]
@Tomtomgo, thanks! I'll do it! However, I can't access your repository. I've tried to push a feature branch, so then I would have created a pull request, but I keep receiving rejection from the repository:

`git push --set-upstream origin ISSUE-5`
`remote: Permission to Tomtomgo/constangular-brunch.git denied to Nickesh.`
`fatal: unable to access 'https://github.com/Tomtomgo/constangular-brunch.git/': The requested URL returned error: 403`

**Comment by Tomtomgo** [comment]
Hi @Nickesh, that makes sense. To create a pull request (PR), you will need to create a fork of this repo, make your changes in your fork, and create a PR from there.

Perhaps it could be useful to check out the Github documentation on this topic: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by Nickesh** [comment]
Thank you so much, @Tomtomgo! Could you also update the package version number, so it has any effect on the NPM library?

https://www.npmjs.com/package/constangular-brunch

I'm mentioning it, because my `npm install constangular-brunch` still causes downloading the previous, buggy version.

**Comment by Tomtomgo** [comment]
@Nickesh done.

**Comment by Nickesh** [comment]
It's perfect now. Thank you and good luck :)
